-- =============================================================
--          MYSQL DATA TYPES - COMPLETE QUICK REFERENCE
-- =============================================================
-- This file is a SUMMARY of all MySQL Data Types.
-- For detailed examples, open the individual topic folders.
-- =============================================================

-- ─────────────────────────────────────────────────────────────
-- NUMERIC TYPES          → 01_Numeric_Types/numeric_types.sql
-- ─────────────────────────────────────────────────────────────
-- TINYINT    → -128 to 127         (1 byte)
-- SMALLINT   → -32768 to 32767     (2 bytes)
-- MEDIUMINT  → -8388608 to 8388607 (3 bytes)
-- INT        → -2B to 2B           (4 bytes)
-- BIGINT     → very large          (8 bytes)
-- FLOAT      → approx 7 digits     (4 bytes)
-- DOUBLE     → approx 15 digits    (8 bytes)
-- DECIMAL(p,s) → exact precision   (varies)
-- BOOLEAN    → 0 or 1 (alias of TINYINT)
-- UNSIGNED   → no negatives, doubles max positive value
-- ZEROFILL   → pads with leading zeros

-- ─────────────────────────────────────────────────────────────
-- STRING TYPES           → 02_String_Types/string_types.sql
-- ─────────────────────────────────────────────────────────────
-- CHAR(n)       → fixed length,    max 255 chars
-- VARCHAR(n)    → variable length, max 65535 chars
-- TINYTEXT      → max 255 bytes
-- TEXT          → max 65 KB
-- MEDIUMTEXT    → max 16 MB
-- LONGTEXT      → max 4 GB
-- ENUM(a,b,...) → one value from a fixed list
-- SET(a,b,...)  → zero or more values from a list

-- ─────────────────────────────────────────────────────────────
-- DATE & TIME TYPES      → 03_DateTime_Types/datetime_types.sql
-- ─────────────────────────────────────────────────────────────
-- DATE          → YYYY-MM-DD
-- TIME          → HH:MM:SS
-- DATETIME      → YYYY-MM-DD HH:MM:SS  (no timezone)
-- TIMESTAMP     → YYYY-MM-DD HH:MM:SS  (UTC, auto-updates)
-- YEAR          → YYYY

-- ─────────────────────────────────────────────────────────────
-- BINARY & BLOB TYPES    → 04_Binary_Blob_Types/binary_blob_types.sql
-- ─────────────────────────────────────────────────────────────
-- BINARY(n)     → fixed binary,   max 255 bytes
-- VARBINARY(n)  → variable binary, max 65535 bytes
-- TINYBLOB      → max 255 bytes
-- BLOB          → max 65 KB
-- MEDIUMBLOB    → max 16 MB  (images, PDFs)
-- LONGBLOB      → max 4 GB   (videos, large files)

-- ─────────────────────────────────────────────────────────────
-- JSON & SPECIAL TYPES   → 05_JSON_Special_Types/json_types.sql
-- ─────────────────────────────────────────────────────────────
-- JSON          → structured key-value / array data (MySQL 5.7+)

-- =============================================================
-- END OF SUMMARY
-- =============================================================
