SHOW DATABASES;
CREATE DATABASE PRACTICE;
USE PRACTICE;
SHOW TABLES;

CREATE TABLE TRIAL1(
	NUM1 TINYINT,
    NUM2 SMALLINT,
    NUM3 MEDIUMINT,
    NUM4 INT,
    NUM5 BIGINT
);
DESC table TRIAL1;
DROP TABLE TRIAL1;

INSERT INTO TRIAL1 VALUES(
    127,
    32767,
    838607,
    21,
    123456789
);
select *from TRIAL1;


create database practice;
use practice;
drop table traile2;
create table traile2(
name char (6) default "SAMPLE"
);

INSERT INTO TRAILE2 VALUES ("APPLE");
INSERT INTO TRAILE2 VALUES ("APPL");
INSERT INTO TRAILE2 VALUES ("APPLESAPPLE");
INSERT INTO TRAILE2 VALUES ("APPL1");
INSERT INTO TRAILE2 VALUES (default);


SELECT * FROM TRAILE2;

DROP TABLE TRIALE3;
CREATE TABLE TRIALE3(
COLM1 VARCHAR(10),
COLM2 VARCHAR(3),
COLM3 CHAR
);

INSERT INTO TRIALE3 VALUES ("APPLES","CHA","4");
INSERT INTO TRIALE3 VALUES ("AP","CHN","A");
INSERT INTO TRIALE3 VALUES ("APPLESAPPLE");

SELECT * FROM TRIALE3;


DROP TABLE TASK3;
CREATE TABLE TASK3(
GENDER ENUM("MALE","FEMALE","OTHERS") DEFAULT (3),
FAV_COLORS SET("GREEN","RED","YELLOW")
);
INSERT INTO TASK3 VALUES(1,2);
INSERT INTO TASK3 VALUES(1,"RED");
INSERT INTO TASK3 VALUES(2,(1 | 4));
INSERT INTO TASK3 VALUES(DEFAULT);


SELECT * FROM TASK3;


ALTER TABLE TASK3
DROP COLUMN GENDER;

ALTER TABLE TRIALE3
DROP COLUMN COLM1;



use practice;
SHOW TABLES;

CREATE TABLE TRIAL7(
EVENT_DATE DATE,
EVENT_TIMESTAMP TIMESTAMP,
EVENT_TIME TIME,
EVENT_YEAR YEAR
);


INSERT INTO TRIAL7 VALUES("2026-10-20","2026-10-20 10:25:02","10:25:02","2027");
INSERT INTO TRIAL7 VALUES(current_date(),current_timestamp(),current_timestamp(),current_date());

SELECT * FROM TRIAL7;




CREATE TABLE TRIAL8(
    EVENT_DATE DATE DEFAULT '2026-01-01',
    EVENT_TIMESTAMP TIMESTAMP DEFAULT '2026-01-01 00:00:00',
    EVENT_TIME TIME DEFAULT '00:00:00',
    EVENT_YEAR YEAR DEFAULT 2026
);

INSERT INTO TRIAL8 VALUES ();
INSERT INTO TRIAL8 VALUES("2026-10-20","2026-10-20 10:25:02","10:25:02","2027");
INSERT INTO TRIAL8 VALUES(current_date(),current_timestamp(),current_timestamp(),current_date());
INSERT INTO TRIAL8 (EVENT_DATE) VALUES (STR_TO_DATE('25-12-2026', '%d-%m-%Y'));

SELECT * FROM TRIAL8;

DROP TABLE IF EXISTS TRAIAL5;

CREATE TABLE TRAIAL5 (
    Event_Date VARCHAR(30)
);

INSERT INTO TRAIAL5 VALUES (DATE_FORMAT(NOW(), '%d - %M - %y'));
INSERT INTO TRAIAL5 VALUES (DATE_FORMAT(NOW(), '%d - %m - %y'));
INSERT INTO TRAIAL5 VALUES (DATE_FORMAT(NOW(), '%d / %b / %y'));
INSERT INTO TRAIAL5 VALUES (DATE_FORMAT(NOW(), '%d / %M / %y' ));
INSERT INTO TRAIAL5 VALUES (DATE_FORMAT(NOW(), '%d / %M / %y %H:%i:%s'));
INSERT INTO TRAIAL5 VALUES (DATE_FORMAT('2026-12-25', '%d - %M - %y'));


SELECT * FROM TRAIAL5;

-- MAKE ONE EXAMPLE FOR TINY INT

DROP TABLE IF EXISTS TRIAL9;

CREATE TABLE TRIAL9 (
    isAgree BOOLEAN
);

INSERT INTO TRIAL9 VALUES (TRUE);
INSERT INTO TRIAL9 VALUES (FALSE);
INSERT INTO TRIAL9 VALUES (10);
INSERT INTO TRIAL9 VALUES (1);
INSERT INTO TRIAL9 VALUES (0);
INSERT INTO TRIAL9 VALUES (-5);
INSERT INTO TRIAL9 VALUES (127);
INSERT INTO TRIAL9 VALUES (NULL);
INSERT INTO TRIAL9 VALUES (10 + 10);

SELECT * FROM TRIAL9;


-- BINARY DATATYPES

CREATE DATABASE PRACTICE;
USE PRACTICE;
DROP TABLE TRAIL01;
CREATE TABLE TRAIL01(
COL1 BLOB
);

INSERT INTO TRAIL01 VALUES("C:/ProgramData/MySQL/MySQL Server 8.0/Data/practice/blob_64KB.bin");


SELECT * FROM TRAIL01;



--  make downlad the data as blob_64kb form chatgpt and paste to  the C:\ProgramData\MySQL\MySQL Server 8.0\Data\practice


CREATE DATABASE PRACTICE;
USE PRACTICE;
DROP TABLE TRAIL01;
CREATE TABLE TRAIL01(
COL1 BLOB
);

INSERT INTO TRAIL01 VALUES("C:/ProgramData/MySQL/MySQL Server 8.0/Data/practice/blob_64KB.bin");


SELECT * FROM TRAIL01;


-- perspective table

-- personal details 
-- name   height   weight  age
-- rahul    5.7      70    25
-- abhi     5.6      55    66

-- constraints: 
-------------------
-- It is restriction that has to be implemeted on the attirube that can validate the data is need to be stored into the table 
-- advantage:
    -- It ensures: data accurnacy, data consistency and data intengrity to cretrain extend
    -- it can control into to conditions ....

-- there are totally 7 constraints 
-- PRIMARY KEY – uniquely identifies each row.
-- FOREIGN KEY – creates a relationship between tables.
-- UNIQUE – prevents duplicate values.
-- NOT NULL – prevents NULL values.
-- CHECK – restricts values according to a condition.
-- DEFAULT – provides a value automatically when none is given